import{a as f,S as g,i as n}from"./assets/vendor-CoddJyDI.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const h="49358433-5727c4bf05d17bed3943eaf07",p="https://pixabay.com/api/",L=15;let b=0;const w=async(t,o=1)=>{try{const r=await f.get(p,{params:{key:h,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:L,page:o}});return b=r.data.totalHits,r.data}catch(r){return console.error("Error fetching images:",r),{hits:[],totalHits:0}}},l=document.querySelector(".gallery"),S=new g(".gallery a",{captionSelector:"img",captionsData:"alt",captionDelay:250}),m=t=>{if(l.innerHTML="",t.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=t.map(r=>`
  <li class="gallery-item">
       <a href="${r.largeImageURL}" class="gallery-link">
        <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${r.likes}</p>
          <p class="info-item"><b>Views:</b> ${r.views}</p>
          <p class="info-item"><b>Comments:</b> ${r.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");l.insertAdjacentHTML("beforeend",o),S.refresh()},u=()=>{document.querySelector(".loader").style.display="block"},c=()=>{document.querySelector(".loader").style.display="none"},q=()=>{l.innerHTML=""},y=()=>{document.querySelector(".load-more").classList.remove("hidden")},d=()=>{document.querySelector(".load-more").classList.add("hidden")},v=()=>{const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})};document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".form"),o=document.querySelector('input[name="search-text"]');document.querySelector(".load-more"),c(),d(),t.addEventListener("submit",async r=>{r.preventDefault();const a=o.value.trim();if(a===""){n.error({message:"Please enter a search term!"});return}q(),d(),u();try{const{hits:e,totalHits:s}=await w(a);e.length===0?n.warning({message:"Sorry, there are no images matching your search query. Please try again!"}):(m(e),e.length<s&&y())}catch(e){n.error({message:"An error occurred while fetching images. Please try again later."}),console.error("Error fetching images:",e)}finally{c()}})});loadMoreBtn.addEventListener("click",async()=>{u();try{const{hits:t,totalHits:o}=await loadMoreImages();t.length>0&&(m(t),v(),t.length<o?y():d())}catch(t){n.error({message:"Error loading more images."}),console.error(t)}finally{c()}});
//# sourceMappingURL=index.js.map
